apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: memorylink-development
  
namespace: memorylink-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development
  
commonAnnotations:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: memorylink
    newTag: dev-latest

replicas:
  - name: memorylink-deployment
    count: 1