apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: memorylink-production
  
namespace: memorylink-prod

resources:
  - ../../base
  - hpa.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml

namePrefix: prod-

commonLabels:
  environment: production
  
commonAnnotations:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
  - service-patch.yaml

images:
  - name: memorylink
    newTag: v1.0.0

replicas:
  - name: memorylink-deployment
    count: 3