apiVersion: v1
kind: PersistentVolume
metadata:
  name: memorylink-data-pv
  labels:
    app: memorylink
    component: storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/memorylink/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1  # Replace with actual node name
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: memorylink-logs-pv
  labels:
    app: memorylink
    component: logs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/memorylink/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1  # Replace with actual node name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memorylink-data-pvc
  namespace: memorylink
  labels:
    app: memorylink
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memorylink-logs-pvc
  namespace: memorylink
  labels:
    app: memorylink
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi